version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"  # location of Gemfile
    schedule:
      interval: "weekly"  # or "daily", "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
